# Generated by Django 4.2.11 on 2024-03-22 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_field_2_post_field_3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='field_2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='field_3',
        ),
    ]
